# This Dockerfile builds the API only.

FROM python:3.9
WORKDIR /app

COPY requirements.txt backend/server.py backend/.flaskenv ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", "5000:5000", "backend:app"]
