services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: qualogy-console-api
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: qualogy-console-client
    ports:
      - "3000:80"
